# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calendar.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basicTypes_pb2 as basicTypes__pb2
import rvtimestamp_pb2 as rvtimestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63\x61lendar.proto\x12\x07rv.data\x1a\x10\x62\x61sicTypes.proto\x1a\x11rvtimestamp.proto\"\xb2\x07\n\x08\x43\x61lendar\x12\'\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x17.rv.data.Calendar.Event\x12\x0e\n\x06\x61\x63tive\x18\x02 \x01(\x08\x1a\xec\x06\n\x05\x45vent\x12\x1b\n\x04uuid\x18\x01 \x01(\x0b\x32\r.rv.data.UUID\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12 \n\x04\x64\x61te\x18\x04 \x01(\x0b\x32\x12.rv.data.Timestamp\x12:\n\x0frecurrence_days\x18\x05 \x03(\x0e\x32!.rv.data.Calendar.Event.DayOfWeek\x12\x31\n\x15recurrence_limit_date\x18\x06 \x01(\x0b\x32\x12.rv.data.Timestamp\x12\x35\n\x19recurrence_excluded_dates\x18\x07 \x03(\x0b\x32\x12.rv.data.Timestamp\x12.\n\x06\x61\x63tion\x18\x08 \x01(\x0b\x32\x1e.rv.data.Calendar.Event.Action\x1a\xd3\x02\n\x06\x41\x63tion\x12\x0c\n\x04type\x18\x01 \x01(\r\x12\x1b\n\x04uuid\x18\x02 \x01(\x0b\x32\r.rv.data.UUID\x12;\n\x08playlist\x18\x03 \x01(\x0b\x32\'.rv.data.Calendar.Event.Action.PlaylistH\x00\x12\x35\n\x05macro\x18\x04 \x01(\x0b\x32$.rv.data.Calendar.Event.Action.MacroH\x00\x1a[\n\x08Playlist\x12$\n\rplaylist_uuid\x18\x01 \x01(\x0b\x32\r.rv.data.UUID\x12)\n\x12playlist_item_uuid\x18\x02 \x01(\x0b\x32\r.rv.data.UUID\x1a?\n\x05Macro\x12\x36\n\x0eidentification\x18\x01 \x01(\x0b\x32\x1e.rv.data.CollectionElementTypeB\x0c\n\nActionType\"\xd4\x01\n\tDayOfWeek\x12\x17\n\x13\x44\x41Y_OF_WEEK_UNKNOWN\x10\x00\x12\x16\n\x12\x44\x41Y_OF_WEEK_SUNDAY\x10\x01\x12\x16\n\x12\x44\x41Y_OF_WEEK_MONDAY\x10\x02\x12\x17\n\x13\x44\x41Y_OF_WEEK_TUESDAY\x10\x03\x12\x19\n\x15\x44\x41Y_OF_WEEK_WEDNESDAY\x10\x04\x12\x18\n\x14\x44\x41Y_OF_WEEK_THURSDAY\x10\x05\x12\x16\n\x12\x44\x41Y_OF_WEEK_FRIDAY\x10\x06\x12\x18\n\x14\x44\x41Y_OF_WEEK_SATURDAY\x10\x07\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calendar_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CALENDAR._serialized_start=65
  _CALENDAR._serialized_end=1011
  _CALENDAR_EVENT._serialized_start=135
  _CALENDAR_EVENT._serialized_end=1011
  _CALENDAR_EVENT_ACTION._serialized_start=457
  _CALENDAR_EVENT_ACTION._serialized_end=796
  _CALENDAR_EVENT_ACTION_PLAYLIST._serialized_start=626
  _CALENDAR_EVENT_ACTION_PLAYLIST._serialized_end=717
  _CALENDAR_EVENT_ACTION_MACRO._serialized_start=719
  _CALENDAR_EVENT_ACTION_MACRO._serialized_end=782
  _CALENDAR_EVENT_DAYOFWEEK._serialized_start=799
  _CALENDAR_EVENT_DAYOFWEEK._serialized_end=1011
# @@protoc_insertion_point(module_scope)
