# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: input.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basicTypes_pb2 as basicTypes__pb2
import graphicsData_pb2 as graphicsData__pb2
import digitalAudio_pb2 as digitalAudio__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0binput.proto\x12\x07rv.data\x1a\x10\x62\x61sicTypes.proto\x1a\x12graphicsData.proto\x1a\x12\x64igitalAudio.proto\"\xa5\x04\n\nVideoInput\x12\x1b\n\x04uuid\x18\x01 \x01(\x0b\x32\r.rv.data.UUID\x12\x18\n\x10user_description\x18\x02 \x01(\t\x12\x36\n\x12video_input_device\x18\x03 \x01(\x0b\x32\x1a.rv.data.Media.VideoDevice\x12%\n\rdisplay_color\x18\x04 \x01(\x0b\x32\x0e.rv.data.Color\x12$\n\x0ethumbnail_path\x18\x05 \x01(\x0b\x32\x0c.rv.data.URL\x12\x37\n\naudio_type\x18\x08 \x01(\x0e\x32#.rv.data.VideoInput.AudioDeviceType\x12\x34\n\x0c\x61udio_device\x18\x06 \x01(\x0b\x32\x1c.rv.data.DigitalAudio.DeviceH\x00\x12\x32\n\x0cvideo_device\x18\x07 \x01(\x0b\x32\x1a.rv.data.Media.VideoDeviceH\x00\x1a\x37\n\x10SettingsDocument\x12#\n\x06inputs\x18\x01 \x03(\x0b\x32\x13.rv.data.VideoInput\"m\n\x0f\x41udioDeviceType\x12\x1d\n\x19\x41UDIO_DEVICE_TYPE_DEFAULT\x10\x00\x12\x1a\n\x16\x41UDIO_DEVICE_TYPE_NONE\x10\x01\x12\x1f\n\x1b\x41UDIO_DEVICE_TYPE_ALTERNATE\x10\x02\x42\x10\n\x0e\x41ltAudioSource\"\xaa\x04\n\nAudioInput\x12\x1b\n\x04uuid\x18\x01 \x01(\x0b\x32\r.rv.data.UUID\x12\x18\n\x10user_description\x18\x02 \x01(\t\x12\x37\n\rbehavior_mode\x18\x05 \x01(\x0b\x32 .rv.data.AudioInput.BehaviorMode\x12\x34\n\x0c\x61udio_device\x18\x03 \x01(\x0b\x32\x1c.rv.data.DigitalAudio.DeviceH\x00\x12\x32\n\x0cvideo_device\x18\x04 \x01(\x0b\x32\x1a.rv.data.Media.VideoDeviceH\x00\x1a\xb7\x02\n\x0c\x42\x65haviorMode\x12\x31\n\x02on\x18\x01 \x01(\x0b\x32#.rv.data.AudioInput.BehaviorMode.OnH\x00\x12\x33\n\x03off\x18\x02 \x01(\x0b\x32$.rv.data.AudioInput.BehaviorMode.OffH\x00\x12:\n\x07\x61uto_on\x18\x03 \x01(\x0b\x32\'.rv.data.AudioInput.BehaviorMode.AutoOnH\x00\x12<\n\x08\x61uto_off\x18\x04 \x01(\x0b\x32(.rv.data.AudioInput.BehaviorMode.AutoOffH\x00\x1a\x04\n\x02On\x1a\x05\n\x03Off\x1a\t\n\x07\x41utoOff\x1a%\n\x06\x41utoOn\x12\x1b\n\x13linked_video_inputs\x18\x01 \x03(\rB\x06\n\x04ModeB\x08\n\x06Sourceb\x06proto3')



_VIDEOINPUT = DESCRIPTOR.message_types_by_name['VideoInput']
_VIDEOINPUT_SETTINGSDOCUMENT = _VIDEOINPUT.nested_types_by_name['SettingsDocument']
_AUDIOINPUT = DESCRIPTOR.message_types_by_name['AudioInput']
_AUDIOINPUT_BEHAVIORMODE = _AUDIOINPUT.nested_types_by_name['BehaviorMode']
_AUDIOINPUT_BEHAVIORMODE_ON = _AUDIOINPUT_BEHAVIORMODE.nested_types_by_name['On']
_AUDIOINPUT_BEHAVIORMODE_OFF = _AUDIOINPUT_BEHAVIORMODE.nested_types_by_name['Off']
_AUDIOINPUT_BEHAVIORMODE_AUTOOFF = _AUDIOINPUT_BEHAVIORMODE.nested_types_by_name['AutoOff']
_AUDIOINPUT_BEHAVIORMODE_AUTOON = _AUDIOINPUT_BEHAVIORMODE.nested_types_by_name['AutoOn']
_VIDEOINPUT_AUDIODEVICETYPE = _VIDEOINPUT.enum_types_by_name['AudioDeviceType']
VideoInput = _reflection.GeneratedProtocolMessageType('VideoInput', (_message.Message,), {

  'SettingsDocument' : _reflection.GeneratedProtocolMessageType('SettingsDocument', (_message.Message,), {
    'DESCRIPTOR' : _VIDEOINPUT_SETTINGSDOCUMENT,
    '__module__' : 'input_pb2'
    # @@protoc_insertion_point(class_scope:rv.data.VideoInput.SettingsDocument)
    })
  ,
  'DESCRIPTOR' : _VIDEOINPUT,
  '__module__' : 'input_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.VideoInput)
  })
_sym_db.RegisterMessage(VideoInput)
_sym_db.RegisterMessage(VideoInput.SettingsDocument)

AudioInput = _reflection.GeneratedProtocolMessageType('AudioInput', (_message.Message,), {

  'BehaviorMode' : _reflection.GeneratedProtocolMessageType('BehaviorMode', (_message.Message,), {

    'On' : _reflection.GeneratedProtocolMessageType('On', (_message.Message,), {
      'DESCRIPTOR' : _AUDIOINPUT_BEHAVIORMODE_ON,
      '__module__' : 'input_pb2'
      # @@protoc_insertion_point(class_scope:rv.data.AudioInput.BehaviorMode.On)
      })
    ,

    'Off' : _reflection.GeneratedProtocolMessageType('Off', (_message.Message,), {
      'DESCRIPTOR' : _AUDIOINPUT_BEHAVIORMODE_OFF,
      '__module__' : 'input_pb2'
      # @@protoc_insertion_point(class_scope:rv.data.AudioInput.BehaviorMode.Off)
      })
    ,

    'AutoOff' : _reflection.GeneratedProtocolMessageType('AutoOff', (_message.Message,), {
      'DESCRIPTOR' : _AUDIOINPUT_BEHAVIORMODE_AUTOOFF,
      '__module__' : 'input_pb2'
      # @@protoc_insertion_point(class_scope:rv.data.AudioInput.BehaviorMode.AutoOff)
      })
    ,

    'AutoOn' : _reflection.GeneratedProtocolMessageType('AutoOn', (_message.Message,), {
      'DESCRIPTOR' : _AUDIOINPUT_BEHAVIORMODE_AUTOON,
      '__module__' : 'input_pb2'
      # @@protoc_insertion_point(class_scope:rv.data.AudioInput.BehaviorMode.AutoOn)
      })
    ,
    'DESCRIPTOR' : _AUDIOINPUT_BEHAVIORMODE,
    '__module__' : 'input_pb2'
    # @@protoc_insertion_point(class_scope:rv.data.AudioInput.BehaviorMode)
    })
  ,
  'DESCRIPTOR' : _AUDIOINPUT,
  '__module__' : 'input_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.AudioInput)
  })
_sym_db.RegisterMessage(AudioInput)
_sym_db.RegisterMessage(AudioInput.BehaviorMode)
_sym_db.RegisterMessage(AudioInput.BehaviorMode.On)
_sym_db.RegisterMessage(AudioInput.BehaviorMode.Off)
_sym_db.RegisterMessage(AudioInput.BehaviorMode.AutoOff)
_sym_db.RegisterMessage(AudioInput.BehaviorMode.AutoOn)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VIDEOINPUT._serialized_start=83
  _VIDEOINPUT._serialized_end=632
  _VIDEOINPUT_SETTINGSDOCUMENT._serialized_start=448
  _VIDEOINPUT_SETTINGSDOCUMENT._serialized_end=503
  _VIDEOINPUT_AUDIODEVICETYPE._serialized_start=505
  _VIDEOINPUT_AUDIODEVICETYPE._serialized_end=614
  _AUDIOINPUT._serialized_start=635
  _AUDIOINPUT._serialized_end=1189
  _AUDIOINPUT_BEHAVIORMODE._serialized_start=868
  _AUDIOINPUT_BEHAVIORMODE._serialized_end=1179
  _AUDIOINPUT_BEHAVIORMODE_ON._serialized_start=1110
  _AUDIOINPUT_BEHAVIORMODE_ON._serialized_end=1114
  _AUDIOINPUT_BEHAVIORMODE_OFF._serialized_start=1116
  _AUDIOINPUT_BEHAVIORMODE_OFF._serialized_end=1121
  _AUDIOINPUT_BEHAVIORMODE_AUTOOFF._serialized_start=1123
  _AUDIOINPUT_BEHAVIORMODE_AUTOOFF._serialized_end=1132
  _AUDIOINPUT_BEHAVIORMODE_AUTOON._serialized_start=1134
  _AUDIOINPUT_BEHAVIORMODE_AUTOON._serialized_end=1171
# @@protoc_insertion_point(module_scope)
