# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: labels.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import action_pb2 as action__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0clabels.proto\x12\x07rv.data\x1a\x0c\x61\x63tion.proto\":\n\x11ProLabelsDocument\x12%\n\x06labels\x18\x01 \x03(\x0b\x32\x15.rv.data.Action.Labelb\x06proto3')



_PROLABELSDOCUMENT = DESCRIPTOR.message_types_by_name['ProLabelsDocument']
ProLabelsDocument = _reflection.GeneratedProtocolMessageType('ProLabelsDocument', (_message.Message,), {
  'DESCRIPTOR' : _PROLABELSDOCUMENT,
  '__module__' : 'labels_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.ProLabelsDocument)
  })
_sym_db.RegisterMessage(ProLabelsDocument)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROLABELSDOCUMENT._serialized_start=39
  _PROLABELSDOCUMENT._serialized_end=97
# @@protoc_insertion_point(module_scope)
