# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: liveVideoPlaylist.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basicTypes_pb2 as basicTypes__pb2
import action_pb2 as action__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17liveVideoPlaylist.proto\x12\x07rv.data\x1a\x10\x62\x61sicTypes.proto\x1a\x0c\x61\x63tion.proto\"~\n\x11LiveVideoPlaylist\x12 \n\x07\x61\x63tions\x18\x01 \x03(\x0b\x32\x0f.rv.data.Action\x12*\n\x13targeted_layer_UUID\x18\x02 \x01(\x0b\x32\r.rv.data.UUID\x12\x1b\n\x04uuid\x18\x03 \x01(\x0b\x32\r.rv.data.UUIDb\x06proto3')



_LIVEVIDEOPLAYLIST = DESCRIPTOR.message_types_by_name['LiveVideoPlaylist']
LiveVideoPlaylist = _reflection.GeneratedProtocolMessageType('LiveVideoPlaylist', (_message.Message,), {
  'DESCRIPTOR' : _LIVEVIDEOPLAYLIST,
  '__module__' : 'liveVideoPlaylist_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.LiveVideoPlaylist)
  })
_sym_db.RegisterMessage(LiveVideoPlaylist)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LIVEVIDEOPLAYLIST._serialized_start=68
  _LIVEVIDEOPLAYLIST._serialized_end=194
# @@protoc_insertion_point(module_scope)
