# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: macros.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basicTypes_pb2 as basicTypes__pb2
import action_pb2 as action__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmacros.proto\x12\x07rv.data\x1a\x10\x62\x61sicTypes.proto\x1a\x0c\x61\x63tion.proto\"\x85\x02\n\x0eMacrosDocument\x12\x32\n\x10\x61pplication_info\x18\x01 \x01(\x0b\x32\x18.rv.data.ApplicationInfo\x12-\n\x06macros\x18\x02 \x03(\x0b\x32\x1d.rv.data.MacrosDocument.Macro\x1a\x8f\x01\n\x05Macro\x12\x1b\n\x04uuid\x18\x01 \x01(\x0b\x32\r.rv.data.UUID\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x1d\n\x05\x63olor\x18\x03 \x01(\x0b\x32\x0e.rv.data.Color\x12 \n\x07\x61\x63tions\x18\x04 \x03(\x0b\x32\x0f.rv.data.Action\x12\x1a\n\x12trigger_on_startup\x18\x05 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'macros_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MACROSDOCUMENT._serialized_start=58
  _MACROSDOCUMENT._serialized_end=319
  _MACROSDOCUMENT_MACRO._serialized_start=176
  _MACROSDOCUMENT_MACRO._serialized_end=319
# @@protoc_insertion_point(module_scope)
