# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proMask.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import slide_pb2 as slide__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproMask.proto\x12\x07rv.data\x1a\x0bslide.proto\";\n\x07ProMask\x12\"\n\nbase_slide\x18\x01 \x01(\x0b\x32\x0e.rv.data.Slide\x12\x0c\n\x04name\x18\x02 \x01(\tb\x06proto3')



_PROMASK = DESCRIPTOR.message_types_by_name['ProMask']
ProMask = _reflection.GeneratedProtocolMessageType('ProMask', (_message.Message,), {
  'DESCRIPTOR' : _PROMASK,
  '__module__' : 'proMask_pb2'
  # @@protoc_insertion_point(class_scope:rv.data.ProMask)
  })
_sym_db.RegisterMessage(ProMask)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROMASK._serialized_start=39
  _PROMASK._serialized_end=98
# @@protoc_insertion_point(module_scope)
