# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: propresenter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basicTypes_pb2 as basicTypes__pb2
import playlist_pb2 as playlist__pb2
import action_pb2 as action__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12propresenter.proto\x12\x07rv.data\x1a\x10\x62\x61sicTypes.proto\x1a\x0eplaylist.proto\x1a\x0c\x61\x63tion.proto\"\xef\x02\n\x10PlaylistDocument\x12\x32\n\x10\x61pplication_info\x18\x01 \x01(\x0b\x32\x18.rv.data.ApplicationInfo\x12,\n\x04type\x18\x02 \x01(\x0e\x32\x1e.rv.data.PlaylistDocument.Type\x12$\n\troot_node\x18\x03 \x01(\x0b\x32\x11.rv.data.Playlist\x12#\n\x04tags\x18\x04 \x03(\x0b\x32\x15.rv.data.Playlist.Tag\x12.\n\x13live_video_playlist\x18\x05 \x01(\x0b\x32\x11.rv.data.Playlist\x12-\n\x12\x64ownloads_playlist\x18\x06 \x01(\x0b\x32\x11.rv.data.Playlist\"O\n\x04Type\x12\x10\n\x0cTYPE_UNKNOWN\x10\x00\x12\x15\n\x11TYPE_PRESENTATION\x10\x01\x12\x0e\n\nTYPE_MEDIA\x10\x02\x12\x0e\n\nTYPE_AUDIO\x10\x03\"9\n\x10SettingsDocument\x12%\n\x06labels\x18\x02 \x03(\x0b\x32\x15.rv.data.Action.Labelb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'propresenter_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYLISTDOCUMENT._serialized_start=80
  _PLAYLISTDOCUMENT._serialized_end=447
  _PLAYLISTDOCUMENT_TYPE._serialized_start=368
  _PLAYLISTDOCUMENT_TYPE._serialized_end=447
  _SETTINGSDOCUMENT._serialized_start=449
  _SETTINGSDOCUMENT._serialized_end=506
# @@protoc_insertion_point(module_scope)
